package com.project.auth_service.enums;

public enum AuditEventType {
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGIN_FAILED,
    USER_LOGGED_OUT,
    USER_LOGGED_OUT_ALL,
    SESSION_REVOKED,
    ALL_SESSIONS_REVOKED,
    REFRESH_TOKEN_ROTATED,
    REFRESH_TOKEN_REUSE_DETECTED,
    ADMIN_ROLE_GRANTED,
    ADMIN_ROLE_REVOKED,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    USER_BANNED,
    USER_UNBANNED,
    SUPER_ADMIN_BOOTSTRAPPED,
    RATE_LIMIT_EXCEEDED,
    AUTH_CLIENT_CREATED,
    AUTH_CLIENT_UPDATED,
    AUTH_CLIENT_ENABLED,
    AUTH_CLIENT_DISABLED
}
